# Generated by Django 2.0.2 on 2018-04-28 22:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('venta_unidades', models.IntegerField()),
                ('venta_pesos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('venta_descuento', models.DecimalField(decimal_places=2, max_digits=14)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.Producto')),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.Tienda')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.SubCategoria'),
        ),
    ]
